spring:
    thymeleaf:
        cache: false

    datasource:
        url: jdbc:mysql://121.40.232.245/ems
        username: root
        password: smart201610

    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        password:
        jedis:
            pool:
                max-active: 8
                max-wait: -1
                min-idle: 0
                max-idle: 8
        timeout: 0

